### üêº Pandas Profiling Report
### üö≤ Seoul Bike Sharing Demand Dataset (Prepared Data)
### üìä Exploratory Data Analysis
Note: This pandas profiling report provides insights and data visualizations on the new prepared dataset generated from the data_preparation.ipynb.

In [1]:
# Import required modules
import pandas as pd
from pandas_profiling import ProfileReport

In [2]:
# Generate the pandas profiling report
df = pd.read_csv("seoul_bike_data_prepared.csv", encoding="utf-8")
df.head()

,Rented Bike Count,Hour,Temperature(¬∞C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(¬∞C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Holiday,Functioning Day,Day,Month,Year,Autumn,Spring,Summer,Winter
0,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,0,1,1,12,2017,0,0,0,1
1,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,0,1,1,12,2017,0,0,0,1
2,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,0,1,1,12,2017,0,0,0,1
3,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,0,1,1,12,2017,0,0,0,1
4,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,0,1,1,12,2017,0,0,0,1

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 19 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Rented Bike Count          8760 non-null   int64
 1   Hour                       8760 non-null   int64
 2   Temperature(¬∞C)            8760 non-null   float64
 3   Humidity(%)                8760 non-null   int64
 4   Wind speed (m/s)           8760 non-null   float64
 5   Visibility (10m)           8760 non-null   int64
 6   Dew point temperature(¬∞C)  8760 non-null   float64
 7   Solar Radiation (MJ/m2)    8760 non-null   float64
 8   Rainfall(mm)               8760 non-null   float64
 9   Snowfall (cm)              8760 non-null   float64
 10  Holiday                    8760 non-null   int64
 11  Functioning Day            8760 non-null   int64
 12  Day                        8760 non-null   int64
 13  Month                      8760 non-null   int64
 14  Year                       8760 non-null   int64
 15  Autumn                     8760 non-null   int64
 16  Spring                     8760 non-null   int64
 17  Summer                     8760 non-null   int64
 18  Winter                     8760 non-null   int64
dtypes: float64(6), int64(13)
memory usage: 1.3 MB

In [4]:
profile = ProfileReport(df, title = "üêº Pandas Profiling Report | üö≤ Seoul Bike Sharing Demand Dataset (Prepared Data)")

# Export report to a HTML file
profile.to_file("pandas_profiling_report.html")

Summarize dataset: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 172/172 [00:15<00:00, 11.45it/s, Completed]
Generate report structure: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 1/1 [00:03<00:00,  3.66s/it]
Render HTML: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 1/1 [00:02<00:00,  2.80s/it]
Export report to file: 100%|‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà‚ñà| 1/1 [00:00<00:00, 27.27it/s]